import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { AssayReport } from '../types';
import { DIMENSION_DISPLAY_NAMES } from '../types';

// Colors
const GOLD = [201, 168, 76] as const;    // #C9A84C
const DARK = [13, 13, 26] as const;      // #0D0D1A
const WHITE = [255, 255, 255] as const;
const LIGHT_GRAY = [200, 200, 210] as const;
const MID_GRAY = [120, 120, 140] as const;
const ROW_EVEN = [22, 22, 40] as const;
const ROW_ODD = [30, 30, 50] as const;
const GREEN = [52, 211, 153] as const;
const AMBER = [251, 191, 36] as const;
const RED = [248, 113, 113] as const;

const DEEP_SIGNAL_NAMES: Record<string, string> = {
  strategic_thinking: 'Strategic Thinking',
  execution_ability: 'Execution Ability',
  leadership_presence: 'Leadership Presence',
  cultural_alignment: 'Cultural Alignment',
  emotional_intelligence: 'Emotional Intelligence',
  domain_depth: 'Domain Depth',
  communication_clarity: 'Communication Clarity',
  adaptability: 'Adaptability',
  innovation_mindset: 'Innovation Mindset',
};

function gateStatusColor(status: string): readonly [number, number, number] {
  if (status === 'passed') return GREEN;
  if (status === 'flagged') return AMBER;
  return RED;
}

function gateStatusLabel(status: string): string {
  if (status === 'passed') return 'PASSED';
  if (status === 'flagged') return 'FLAGGED';
  return 'FAILED';
}

function recommendationLabel(rec: string): string {
  if (rec === 'hire') return 'HIRE';
  if (rec === 'do_not_proceed') return 'DO NOT PROCEED';
  return 'CAUTIOUS - BELOW BAR';
}

function drawPageFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  // Separator line
  doc.setDrawColor(...MID_GRAY);
  doc.setLineWidth(0.3);
  doc.line(20, pageH - 18, pageW - 20, pageH - 18);
  // Left: branding
  doc.setFontSize(7);
  doc.setTextColor(...MID_GRAY);
  doc.text('Generated by ASSAY AI', 20, pageH - 12);
  // Center: timestamp
  const ts = new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  doc.text(ts, pageW / 2, pageH - 12, { align: 'center' });
  // Right: page number
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 20, pageH - 12, { align: 'right' });
}

function drawGoldBar(doc: jsPDF) {
  const pageW = doc.internal.pageSize.getWidth();
  // Dark header bar
  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageW, 32, 'F');
  // Gold accent line
  doc.setFillColor(...GOLD);
  doc.rect(0, 32, pageW, 2, 'F');
  // ASSAY text
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GOLD);
  doc.text('ASSAY', 20, 22);
  // Subtitle
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  doc.text('Executive Assessment Report', 56, 22);
}

function scoreColor(score: number): readonly [number, number, number] {
  if (score >= 7.5) return GREEN;
  if (score >= 5) return AMBER;
  return RED;
}

export function generateExecutivePDF(report: AssayReport): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();

  // ────────────────────────── PAGE 1: Executive Summary ──────────────────────────

  drawGoldBar(doc);

  let y = 44;

  // Candidate name
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text(report.candidateName, 20, y);
  y += 8;

  // Role
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  doc.text(report.roleName, 20, y);
  y += 6;

  // Date
  doc.setFontSize(9);
  doc.setTextColor(...MID_GRAY);
  const dateStr = new Date(report.createdAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  doc.text(`Assessment Date: ${dateStr}`, 20, y);
  y += 12;

  // Gate Banner
  const statusColor = gateStatusColor(report.gateBanner.status);
  const statusLabel = gateStatusLabel(report.gateBanner.status);

  // Banner background
  doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.roundedRect(20, y, pageW - 40, 20, 3, 3, 'F');

  // Banner text
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text(statusLabel, pageW / 2, y + 9, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(report.gateBanner.message, pageW / 2, y + 15, { align: 'center' });
  y += 28;

  // Overall Score
  const overallScore = report.pyramidScore.overall;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GOLD);
  doc.text('OVERALL SCORE', 20, y);
  y += 2;

  // Score circle area
  const sc = scoreColor(overallScore);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(sc[0], sc[1], sc[2]);
  doc.text(overallScore.toFixed(1), 20, y + 16);

  // Purity rating next to score
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  doc.text(`Purity Rating: ${report.pyramidScore.purityRating}`, 55, y + 6);

  // Hire bar
  doc.setTextColor(...MID_GRAY);
  doc.setFontSize(9);
  const barStatus = report.pyramidScore.meetsBar ? 'Meets hire bar' : 'Below hire bar';
  doc.text(`Hire Bar: ${report.pyramidScore.hireBar.toFixed(1)} | ${barStatus}`, 55, y + 12);
  y += 24;

  // Executive Summary
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GOLD);
  doc.text('EXECUTIVE SUMMARY', 20, y);
  y += 5;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  const summaryLines = doc.splitTextToSize(report.executiveSummary, pageW - 40);
  // Limit to fit page
  const maxSummaryLines = Math.min(summaryLines.length, 12);
  doc.text(summaryLines.slice(0, maxSummaryLines), 20, y);
  y += maxSummaryLines * 4.2 + 6;

  // Pyramid Score Table
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GOLD);
  doc.text('PYRAMID DIMENSIONS', 20, y);
  y += 3;

  const dimData = report.pyramidScore.dimensions.map(d => {
    const displayName = DIMENSION_DISPLAY_NAMES[d.dimension] || d.dimension;
    const weight = `${(d.weight * 100).toFixed(0)}%`;
    const score = d.score.toFixed(1);
    return [displayName, weight, score];
  });

  autoTable(doc, {
    startY: y,
    head: [['Dimension', 'Weight', 'Score']],
    body: dimData,
    margin: { left: 20, right: 20 },
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: [...LIGHT_GRAY],
      lineWidth: 0,
    },
    headStyles: {
      fillColor: [...DARK],
      textColor: [...GOLD],
      fontStyle: 'bold',
      lineWidth: 0,
    },
    alternateRowStyles: {
      fillColor: [...ROW_EVEN],
    },
    bodyStyles: {
      fillColor: [...ROW_ODD],
    },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 25, halign: 'center' },
      2: { cellWidth: 25, halign: 'center' },
    },
    didParseCell(data) {
      // Color-code score column
      if (data.section === 'body' && data.column.index === 2) {
        const val = parseFloat(data.cell.raw as string);
        const c = scoreColor(val);
        data.cell.styles.textColor = [c[0], c[1], c[2]];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    theme: 'plain',
  });

  // ────────────────────────── PAGE 2: Detailed Analysis ──────────────────────────

  doc.addPage();
  drawGoldBar(doc);
  y = 44;

  // Deep Signals Table
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GOLD);
  doc.text('DEEP SIGNAL ANALYSIS', 20, y);
  y += 3;

  const signalData = report.pyramidScore.deepSignals.map(s => {
    const name = DEEP_SIGNAL_NAMES[s.signal] || s.signal;
    const score = s.score.toFixed(1);
    return [name, score];
  });

  autoTable(doc, {
    startY: y,
    head: [['Signal', 'Score']],
    body: signalData,
    margin: { left: 20, right: 20 },
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: [...LIGHT_GRAY],
      lineWidth: 0,
    },
    headStyles: {
      fillColor: [...DARK],
      textColor: [...GOLD],
      fontStyle: 'bold',
      lineWidth: 0,
    },
    alternateRowStyles: {
      fillColor: [...ROW_EVEN],
    },
    bodyStyles: {
      fillColor: [...ROW_ODD],
    },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 25, halign: 'center' },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 1) {
        const val = parseFloat(data.cell.raw as string);
        const c = scoreColor(val);
        data.cell.styles.textColor = [c[0], c[1], c[2]];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    theme: 'plain',
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // Key Strengths & Concerns
  const strengths: string[] = [];
  const concerns: string[] = [];
  report.deepAssessment.forEach(da => {
    da.strengths.forEach(s => strengths.push(s));
    da.concerns.forEach(c => concerns.push(c));
  });

  if (strengths.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GREEN);
    doc.text('KEY STRENGTHS', 20, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...LIGHT_GRAY);
    const topStrengths = strengths.slice(0, 5);
    topStrengths.forEach(s => {
      const lines = doc.splitTextToSize(`+ ${s}`, pageW - 44);
      doc.text(lines, 24, y);
      y += lines.length * 3.8 + 1;
    });
    y += 4;
  }

  if (concerns.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...RED);
    doc.text('KEY CONCERNS', 20, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...LIGHT_GRAY);
    const topConcerns = concerns.slice(0, 5);
    topConcerns.forEach(c => {
      const lines = doc.splitTextToSize(`- ${c}`, pageW - 44);
      doc.text(lines, 24, y);
      y += lines.length * 3.8 + 1;
    });
    y += 4;
  }

  // Deliberation Summary
  if (y < 230) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GOLD);
    doc.text('DELIBERATION SUMMARY', 20, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...LIGHT_GRAY);
    const synthLines = doc.splitTextToSize(report.deliberation.chairmanSynthesis, pageW - 40);
    const maxLines = Math.min(synthLines.length, 10);
    doc.text(synthLines.slice(0, maxLines), 20, y);
    y += maxLines * 3.8 + 8;
  }

  // Final Recommendation
  if (y < 260) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GOLD);
    doc.text('FINAL RECOMMENDATION', 20, y);
    y += 6;

    const recLabel = recommendationLabel(report.deliberation.finalRecommendation);
    const recColor = report.deliberation.finalRecommendation === 'hire' ? GREEN
      : report.deliberation.finalRecommendation === 'do_not_proceed' ? RED : AMBER;

    doc.setFillColor(recColor[0], recColor[1], recColor[2]);
    doc.roundedRect(20, y, 60, 10, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK);
    doc.text(recLabel, 50, y + 7, { align: 'center' });
  }

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPageFooter(doc, i, totalPages);
  }

  // Save
  const safeName = report.candidateName.replace(/\s+/g, '_');
  doc.save(`ASSAY_${safeName}_Assessment.pdf`);
}
